version = 1
SPDX-PackageName = "capire-orders-java"
SPDX-PackageSupplier = "The cap team <cap@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/capire/orders-java"
SPDX-PackageComment = "This project contians a sample order management application based on the SAP CAP Java framework."

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 SAP SE or an SAP affiliate company and cds-dbs contributors"
SPDX-License-Identifier = "Apache-2.0"
